server:
  port: 8080

anthropic:
  api:
    key: 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
  model: claude-3-5-sonnet-20240620

mongodb:
  connection:
    string: mongodb://admin:password@localhost:27017/admin
  database: chatbot
  collection: embeddings

spring:
  jackson:
    serialization:
      indent-output: true