server:
  port: 8080

anthropic:
  api:
    key: ${KEY}
  model: claude-3-5-sonnet-20240620

mongodb:
  connection:
    string: mongodb://admin:password@localhost:27017/admin
  database: chatbot
  collection: embeddings

spring:
  jackson:
    serialization:
      indent-output: true